### PR TITLE
add regular seek

### PR DESCRIPTION
**Pull request by thaJeztah**
I'm not the original author of this patch, but trying to see if this patch can be upstreamed. BuildKit (https://github.com/moby/buildkit) has been using a fork of this project with this patch applied for the last 3 years; depending on a fork is not "ideal", so I'm opening this pull request to discuss the option of upstreaming this patch (also see the discussion on https://github.com/tonistiigi/go-immutable-radix/pull/1).

I must admit that I don't have a lot of background around the purpose of this patch, so pinging @tonistiigi to provide more details if needed (also if tests are needed (happy to give you write access to my branch, or apply additional patches))

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @banks ptal

/cc @tonistiigi @AkihiroSuda @hinsun  (BuildKit maintainers)

**Comment by thaJeztah** [comment]
Hmm.. looks like @tonistiigi has to sign the CLA as well

**Comment by banks** [comment]
Hi @thaJeztah thanks for the background. I'm glad to hear this has been helping out in BuildKit.

I'd _guess_ the intention of this patch from reading it was to allow for "range scans" i.e: seek to a prefix and then return a `Seeker` that will iterate over each key greater than or equal to that prefix.

The good news (kinda) is that I recently added equivalent functionality to this library. See #24. The naming and API are slightly different but it's already here and as far as I can see does the same thing (and has tests!).

Would you be able to confirm that it meets your needs as I'd rather not merge another interface to do the same thing?

**Comment by thaJeztah** [comment]
That sounds great! I'll let the BuildKit maintainers have a look (as I'm really not familiar with this library or its use myself); if the new feature would work, we can close this PR (and I'm a happy person 🎉)

**Comment by thaJeztah** [comment]
Closing in favour of https://github.com/hashicorp/go-immutable-radix/pull/39 (thanks!)

**Pull request closed without merging**
