### PR TITLE
gofmt all files

### PR DESCRIPTION
**Pull request by thaJeztah**
noticed there were some diffs

### CODE REVIEW

**Comment by thaJeztah** [comment]
@banks PTAL 🤗

**Comment by thaJeztah** [comment]
Oh, good one (to be honest, I forgot about this PR, and spotted it when I headed here for the other PR); let me run `gofmt`  with Go 1.13/1.14 to be sure it was with a current version.

**Comment by thaJeztah** [comment]
All good; rebased, and re-ran `gofmt` on Go 1.14.2, which didn't produce a diff, so it should be current 👍

**Comment by banks** [comment]
Thanks!

**Pull request merged**
